Первая лаба (по junit)
Sakralen/hsai-automated-testing-Grigorii-Spasov pull request #1
Opened 2023-05-08 20:23 UTC by Sakralen

Епам либо троллит с тангенсом, либо лыжи не едут

2023-05-16 20:38 UTC, Shukshin-test requested changes

2023-05-16 20:38 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework1/calculatortests/DivLongTests.java
> +public class DivLongTests extends CalculatorTests {
Убрать модификаторы public в соответствии с https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

2023-05-16 20:38 UTC, Shukshin-test commented on pom.xml
>            <artifactId>maven-surefire-plugin</artifactId>
Лишние плагины бы убрать

2023-05-17 18:07 UTC, Sakralen commented
@Shukshin-test поправил

2023-05-17 18:55 UTC, Shukshin-test approved these changes
done

2023-05-17 21:54 UTC, merged