Вторая лаба (по testng и webdriver)
Sakralen/hsai-automated-testing-Grigorii-Spasov pull request #2
Opened 2023-05-10 01:09 UTC by Sakralen

2023-05-16 20:45 UTC, Shukshin-test requested changes
https://en.wikipedia.org/wiki/Magic_number_(programming)

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task1Test.java
> +        softAssert.assertEquals(benefitTexts.stream().map(WebElement::getText).toList(),
https://www.baeldung.com/java-text-blocks

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task1Test.java
> +        softAssert.assertEquals(benefitTexts.size(), 4);
magic number

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task1Test.java
> +        softAssert.assertEquals(benefitImages.size(), 4);
magic number

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task1Test.java
> +        softAssert.assertEquals(headerItems.size(), 4);
magic number

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task2Test.java
> +                .split("\n")).map(line -> line.substring(9)).toList();
magic number

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/DriverSetup.java
> +        driver.findElements(By.className("dropdown-toggle")).get(1).click();
magic number

2023-05-16 20:45 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task2Test.java
> +        driver.findElements(By.className("dropdown-toggle")).get(0).click();
magic number

2023-05-17 19:36 UTC, Sakralen commented
@Shukshin-test и эту поправил

2023-05-18 21:02 UTC, Shukshin-test approved these changes
gg

2023-05-18 21:02 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task2Test.java
> +        driver.findElement(By.cssSelector("body > header > div > nav > ul.uui-navigation.nav.navbar-nav.m-l8 > li > a > span")).click();
Вот это прям хорошо сделано теперть

2023-05-18 21:02 UTC, Shukshin-test commented on src/test/java/edu/hsai/homework2/Task2Test.java
> +        final int LOGS_BEGIN_INDEX = 9;
А вот это так себе, но с пивом покатит

2023-05-19 15:10 UTC, Sakralen commented on src/test/java/edu/hsai/homework2/Task2Test.java
> +        final int LOGS_BEGIN_INDEX = 9;
да я просто сковырял эти поля из 3ей)

2023-05-19 15:17 UTC, merged